org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true


# Fabric Properties
# https://fabricmc.net/develop
# https://modrinth.com/mod/fabric-api
fabric_loader_version=0.18.4
fabric_api_version=0.119.4+1.21.4


figura_version=0.1.6
luaj_version = 3.0.8
nv_websocket_version = 2.14

wonky_version = 0.0.1
