org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
java_version=17

minecraft_version=1.21.4
mappings = 3
enabled_platforms=fabric

archives_base_name=wonkyplugin
mod_version=0.0.1
maven_group=io.github.dewsmith0.wonkyplugin

# Meta Properties
plugin_id = wonkyplugin
display_name = Figura Wonky Plugin
description = Random wonky additions
authors = Dewsmith

# Fabric Properties
# https://fabricmc.net/develop
# https://modrinth.com/mod/fabric-api
fabric_loader_version=0.18.4
fabric_api_version=0.119.4+1.21.4


# Figura Version
# https://maven.figuramc.org/#/
figura_version=0.1.5

# Libraries
# https://github.com/FiguraMC/luaj
# https://github.com/TakahikoKawasaki/nv-websocket-client
luaj = 3.0.8
nv_websocket = 2.14